# ===================================================================
# Spring Boot configuration - Application
# ===================================================================
server:
  port: 8080
  compression:
    enabled: true
    mime-types:
    - application/json
  servlet:
    context-path: /bideafactory
      
spring:
  application.name: demoreserva-parent
  jackson:
    serialization: 
      indent-output: true
  datasource:
      driver-class-name: org.postgresql.Driver
      url: jdbc:postgresql://127.0.0.1:5432/postgres # jdbc:postgresql://172.30.40.248:5432/ControlSenseDB
      name: postgres #ControlSenseDB
      username: postgres #reader
      password: MiRo220985330 ##Reader
      type: com.zaxxer.hikari.HikariDataSource
      hikari:
        pool-name: hikari-pool
        maximum-pool-size: 3
        connection-timeout: 60000
  jpa:
      database-platform: org.hibernate.dialect.PostgreSQLDialect
      database: POSTGRESQL
      show-sql: true
      properties:
          hibernate.cache.use_second_level_cache: false
          hibernate.cache.use_query_cache: false
          hibernate.generate_statistics: true
          hibernate.id.new_generator_mappings: true 
          hibernate.jdbc.batch_size: 30
          hibernate.jdbc.time_zone: UTC
      hibernate:
        naming:
          physical-strategy: org.hibernate.boot.model.naming.PhysicalNamingStrategyStandardImpl
